### ISSUE TITLE
What specific features of the Google Game Services ANE requires the PermissionCheck.SOURCE_STORAGE on Android?

### ISSUE THREAD

**Issue by MAC-Joyco** [myflashlab/GameServices-ANE#10]
I am targeting AIR 24 and I see two optional permissions required by the Google Game Services ANE:

    PermissionCheck.SOURCE_CONTACTS
    PermissionCheck.SOURCE_STORAGE

I do not need to receive the player email address or access token ID, so I think I do not need SOURCE_CONTACTS, but I am not sure about if I need SOURCE_STORAGE. I did not find information about this in the documentation:
https://github.com/myflashlab/GameServices-ANE#permissions

What specific features of the Google Game Services ANE requires the PermissionCheck.SOURCE_STORAGE on Android?

If I do not need those permissions, Can I simply set the targetSdkVersion to a number lower than 23 without problems on AIR 24 for Android?

Thanks in advance!

**Comment by myflashlab** [comment]
> Can I simply set the targetSdkVersion to a number lower than 23 without problems on AIR 24 for Android?

Yes you can. You may find this blog helpful.
http://www.myflashlabs.com/understanding-android-ios-permissions-in-adobe-air-apps/

> SOURCE_STORAGE

This is needed for internal ANE works on Achievements when it requires to load images.
