### ISSUE TITLE
how to set keychain-access-groups value in Entitlement

### ISSUE THREAD

**Issue by jimmymjing** [myflashlab/GameServices-ANE#11]
I read the wiki and it says we could open the provisioning profile and find out how to setup values for entitlements part. but I find this file is encrypted...
I'm quite confused by entitlement part and how to set these values...

**Comment by myflashlab** [comment]
The provision files are always encrypted but not all of them. If you are opening them with a text editor you must see the ```Entitlements``` section.

**Comment by myflashlab** [comment]
The iOS support has been dropped by Google, so we are closing this issue also.
