### ISSUE TITLE
calling showNativeWindowInvitePlayers() got no friend list nor the back arrow

### ISSUE THREAD

**Issue by jimmymjing** [myflashlab/GameServices-ANE#12]
I called showNativeWindowInvitePlayers() but got no friend list and I don't get the back arrow as shown on the wiki page.. If I click the first head Icon the app simply quits..
Please let me know what I have not yet implemented...btw, create room and quick match works fine.

![img_0397](https://cloud.githubusercontent.com/assets/17842855/23858314/f854012c-083a-11e7-8938-8f61e2b632ef.PNG)

**Comment by myflashlab** [comment]
We are not able to duplicate this 😕 Will you be able to provide more information?

**Comment by myflashlab** [comment]
I'm closing this issue due to lack of reply but if you still have a question, please let us know so we can re-open it. Thanks.
