### ISSUE TITLE
Display custom waiting room UI

### ISSUE THREAD

**Issue by jimmymjing** [myflashlab/GameServices-ANE#13]
Hello, I would like to display a custom waiting room UI after calling: `GameServices.google.multiplayerRealTime.createRoom()`
I tried `GameServices.google.multiplayerRealTime.dismissNativeWaitingRoom()`, but I still got the default waiting room UI from google... I also checked the REST API and I find Rooms: create can not be called.

**Comment by myflashlab** [comment]
The job of the ```createRoom``` is to create a room while the native UI opens. We haven't tried to create custom UIs for that.
