### ISSUE TITLE
RESULT_SIGN_IN_FAILED

### ISSUE THREAD

**Issue by kyoshyro86** [myflashlab/GameServices-ANE#18]
I build your example is Ok but login not success
Error log : onLoginError: RESULT_SIGN_IN_FAILED.
Can you help me with this Error?

**Comment by myflashlab** [comment]
will you be able to provide more information? like your manifest and your AS code, or if a crash happens?

**Comment by kyoshyro86** [comment]
I download your example and buil it with your manifest. I build with air
sdk 26.0. And my device exits 3 gmail acount.

Vào 24-08-2017 19:58, "MyFlashLabs" <notifications@github.com> đã viết:

**Comment by myflashlab** [comment]
PLease check out the following links:

https://developers.google.com/android/reference/com/google/android/gms/games/GamesActivityResultCodes.html#RESULT_SIGN_IN_FAILED

https://stackoverflow.com/a/39779448/247658

**Comment by kyoshyro86** [comment]
Ok Thanks, i'll make new account gmail and try another device. 👍

**Comment by Pingnator** [comment]
Hi there,

I'm struggling with the same issue. I really do not know why I always receive this error message:
onLoginError:  RESULT_SIGN_IN_FAILED
onClientConnectionFailure ****** RESULT_SIGN_IN_FAILED

I just used the LoginSample.as class (with Air SDK 28), included all necessary extensions and linked it to my application (identical App-ID and Package ID). I went through the Google Console documentation as well but I didn't find any helpful information. Is there something else I forgot to set up?

**Comment by myflashlab** [comment]
Just released V4.0.0 of this ANE and this ANE now uses the GoogleSignIn ANE to take care of the authentication. Update yourself and make sure to read the new Wiki to see how you should do things. If any problem, please open a new issue because authentication inside the GameServices ANE is no longer relevant.
