### ISSUE TITLE
Crash App on Android

### ISSUE THREAD

**Issue by Gamezhero** [myflashlab/GameServices-ANE#2]
My app ID: 664133910762
Air SDK 22 (25 May)

http://prntscr.com/bimbxw
http://prntscr.com/bimirc
http://prntscr.com/bimcy0
http://prntscr.com/bime3s
http://prntscr.com/bimey3 (framework for ios too)
http://prntscr.com/bimh9c (included anes v20)

My app on google play: 
https://play.google.com/store/apps/details?id=air.com.rightfusion.crashzilla

Try to press score or medals button on main menu (right-top of screen)
I see google service inititalization and then crash

**Comment by myflashlab** [comment]
In the Android studio logcat, we are seeing this error message when your app tries to login to games services:

```
Authorization failed: server returned error: Access Not Configured. Drive API has not been used in project 664133910762 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive/overview?project=664133910762 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.. See https://developers.google.com/drive/handle-errors for details.
```

For detailed debugging, you should use logcat in Android Studio for Android apps and the console window in xcode for iOS apps.

Anyway, are you having this problem in your final app or you are experiencing this on debug tests also?

Take the Google suggestion described in the message above and see how it goes.

**Comment by Gamezhero** [comment]
enabled on this url https://console.developers.google.com/apis/api/drive/overview?project=664133910762
work... How I miss it..

**Comment by myflashlab** [comment]
good. just make sure you are using Android Studio and xcode for detailed debugging. Good luck with your app. it looks awesome.

**Comment by agnithegreat** [comment]
I have the same issue here. When I call GameServices.google.auth.isLogin or GameServices.google.auth.login(), the app is just crash, and I can't find the error in logcat. I have followed instructions and have set the actual APP_ID in descriptor.xml, but that still makes no sense. Also I have added Drive API as said above, but still no effect. What am I missing?
