### ISSUE TITLE
duplicate symbols error and "Compilation failed while executing : ld64"

### ISSUE THREAD

**Issue by bustahcakes** [myflashlab/GameServices-ANE#20]
## Environment ##
* Android API Version: 26
* iOS Version: 10.3.3
* AIR SDK Version: 27 (tried on 26 as well)

I've just got the ANE to work on Android but I keep getting "duplicate symbol" errors when compiling it on the iOS. GoogleSignIn, gpg, and GoogleOpenSource frameworks are now in my AIR_SDK stub folder. GoogleSignIn and gpg bundle resource files are pasted next to my main.swf in the bin folder. Still no success. 

**duplicate symbol _OBJC_CLASS_$_GTMLogStandardFormatter in:
    /Applications/Adobe Flash Builder 4.7/eclipse/plugins/com.adobe.flash.compiler_4.7.0.349722/AIRSDK/lib/aot/stub/GoogleOpenSource.framework/GoogleOpenSource(GTMLogger.o)
    /Applications/Adobe Flash Builder 4.7/eclipse/plugins/com.adobe.flash.compiler_4.7.0.349722/AIRSDK/lib/aot/stub/GoogleToolboxForMac.framework/GoogleToolboxForMac(GTMLogger_4094a95a437e07e3949458626f85f657.o)
...
...
ld: 23 duplicate symbols for architecture armv7
Compilation failed while executing : ld64**

That's just a section of the long list of similar errors. But they all point to the GoogleOpenSource.framework and GoogleToolboxForMac.framework files. I got GoogleToolboxForMac from following instructions on how to include your AdMob ANE.

After googling around, I found a suggestion to "Hide ANE-Library Symbols" on the Actionscript Build Package settings and that seemed to eliminate the "duplicate symbols" errors. However, I'm left with one error that says: **Compilation failed while executing : ld64** and nothing else.

here's my manifest:

<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/27.0">
	<iPhone>
	    <InfoAdditions>
	    	<![CDATA[
				<key>MinimumOSVersion</key>
				<string>8.0</string>
				
				
				<key>com.google.android.gms.games.APP_ID</key>
				<string>214873947833-r2h6v2odgd6v3m8flojnvri1hhpo5ktm.apps.googleusercontent.com</string>
				
				<key>UIStatusBarStyle</key>
				<string>UIStatusBarStyleBlackOpaque</string>
				
				<key>UIRequiresPersistentWiFi</key>
				<string>NO</string>
				
		        <key>UIFileSharingEnabled</key>
		        <false />
		       
		        <key>UIPrerenderedIcon</key>
		        <true />
				
				<key>FacebookAppID</key>
				<string>371895469896905</string>
				
				<key>FacebookDisplayName</key>
				<string>CheepcheepChivalry</string>
				
				
				
				<key>LSApplicationQueriesSchemes</key>
				<array>
					<string>fbapi</string>
					<string>fb-messenger-api</string>
					<string>fbauth2</string>
					<string>fbshareextension</string>
				</array>
				
				<key>NSCalendarsUsageDescription</key>
				<string>Not in use.</string>
				
				<key>NSCameraUsageDescription</key>
				<string>Not in use.</string>
				
				<key>NSPhotoLibraryUsageDescription</key>
				<string>CheepcheepChivalry will save this image in this device.</string>
				
				<key>NSAppTransportSecurity</key>
				<dict>
					<key>NSAllowsArbitraryLoads</key>
					<true/>
				</dict>
				
				<key>UIDeviceFamily</key>
				<array>
					<string>1</string>
					<string>2</string>
				</array>
						
				<key>UIBackgroundModes</key>
				<array>
					<string>fetch</string>
					<string>remote-notification</string>
				</array>
			]]>
		</InfoAdditions>
	<requestedDisplayResolution>high</requestedDisplayResolution>
       <Entitlements> 
	       <!  [CDATA[ 
		 	        <key>aps-environment</key>
		 	        <string>development</string>
	 
		 	        <key>get-task-allow</key>
		  		    <true/>
	
		 		    <key>beta-reports-active</key>
		 		    <true/>
		 		      
		 		    <key>keychain-access-groups</key>
					<array>
						<string>XXXXXXXXX.*</string>		
					</array>
					
					<key>application-identifier</key>
					<string>XXXXXXXXX.com.site.myapp</string>
					
					<key>com.apple.developer.team-identifier</key>
					<string>XXXXXXXXX</string>
	 	       ]]> 	 	
	    </Entitlements> 
	</iPhone>
    <extensions>
    	<extensionID>com.myflashlab.air.extensions.facebook</extensionID>
    	<extensionID>com.myflashlab.air.extensions.billing</extensionID>
    	<extensionID>com.myflashlab.air.extensions.admob</extensionID>
    	<extensionID>com.myflashlab.air.extensions.gameServices</extensionID>
    	<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
    	<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
	    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>
	    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
	    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.drive</extensionID>
	    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.games</extensionID>
	    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.plus</extensionID>
    	<extensionID>com.milkmangames.extensions.GameCenter</extensionID>
    </extensions>
</application>

**Comment by myflashlab** [comment]
As stated [here](https://github.com/myflashlab/GameServices-ANE#notice-google-has-discontinued-the-game-services-project-for-ios-although-it-will-work-until-31st-march-2018-it-will-not-be-updated-or-maintained-anymore-for-more-information-read-the-official-announcement-here-we-will-continue-maintaining-the-android-side-of-this-ane-as-usual-considering-that-the-ios-side-is-discontinued-we-have-reduced-the-ane-price-by-half) Game services for ios is no longer maintained by Google.

> NOTICE: Google has discontinued the Game Services Project for iOS. Although it will work until 31st March 2018, it will not be updated or maintained anymore. For more information, read....
