### ISSUE TITLE
Is turn-based coming

### ISSUE THREAD

**Issue by leossmith** [myflashlab/GameServices-ANE#21]
I was wondering if you will be adding turn-based in the ANE any time soon. 

Thank you.

**Comment by myflashlab** [comment]
We just released V4.0.0 with all new features. and the native side of TurnBased is ready but not yet available to AIR... we have to finish the other ANE updates we have on the table and then we'll add the turnBased thing to this ANE. This is fixed and confirmed in our to-do list so, I'm closing this issue. As soon as it's released, you'll know.
