### ISSUE TITLE
Saved Games only allows to save Strings?

### ISSUE THREAD

**Issue by Jacowaco** [myflashlab/GameServices-ANE#23]
Hi! I wanted to use Saved Games and found that GameServices.google.snapshots.save() only allows to save Strings while the Google API allows to writeBytes, which could be implemented with ByteArrays:
https://developers.google.com/games/services/android/savedgames

Will you implement the ByteArray functionality? Or should i transform Strings to ByteArrays and vice-versa?

**Comment by myflashlab** [comment]
The current workaround is to use something like Base64 to convert Bytes to String and vice-versa. This is working flawlessly.

**Comment by myflashlab** [comment]
We just released V4.0.0 of the ANE and a LOT has changed but still, the best option for saving content is Strings. You may save a Json string and encode your bytes to String with Base64 encoding. We don't think we would ever change this but it shouldn't be a barrier anyway.
