### ISSUE TITLE
Scopes specification for auth tokens?

### ISSUE THREAD

**Issue by noamgat** [myflashlab/GameServices-ANE#24]
Hi,

Google has started deprecating some of the google play services authentication APIs, urging apps to migrate to the new method:
https://developers.google.com/identity/sign-in/android/migration-guide

This method allows to get a server-verifiable token without requesting anything except the "Manage your activity for this game" permission (So GET_ACCOUNTS is not needed).

Is this possible with the current ANE? From the examples it looks like GET_ACCOUNTS is always needed.

**Comment by myflashlab** [comment]
our recent [GoogleSignIn ANE](https://www.myflashlabs.com/product/google-signin-ane-adobe-air-native-extension/) is using the latest native SDKs. Yet, we are adding some features to it mainly the refreshToken. Please test that ANE and monitor the upcoming changes.

**Comment by myflashlab** [comment]
We are updating the GameService ANE with the latest changes.
