### ISSUE TITLE
Need version code for Google Play Services (downloaded ANE on 23/08/16)

### ISSUE THREAD

**Issue by R24BRX** [myflashlab/GameServices-ANE#3]
I need the version code for the Google Play Services version used to place in the xml file to avoid the compiler error: "AndroidManifest.xml:68: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version')."

**Comment by myflashlab** [comment]
You should enter exactly ```<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />``` in your manifest. However, you will receive the missing resource error message if you have not included all the dependency ANEs. Please make sure you have read this section and have added the dependencies: https://github.com/myflashlab/GameServices-ANE#requirements

**Comment by R24BRX** [comment]
Thanks for the reply, I've solved the issue now, the ANE was not being packaged into the application and I had to toggle the settings for it in the project properties under "Actionscript Build packaging"- the reason why this error was occurring was due to the default setting in the Flash Builder 4.7 IDE which doesn't package ANEs by default.

Yet again thank you for the quick reply.

**Comment by R24BRX** [comment]
![image](https://cloud.githubusercontent.com/assets/20933512/17889346/a93459fa-6927-11e6-9a9c-525d7de5cee9.png)
