### ISSUE TITLE
rewarded video crash.

### ISSUE THREAD

**Issue by giovanni-campos** [myflashlab/GameServices-ANE#30]
## Problem Description ##
I keep getting the fatal exception below when trying to watch rewarded videos, on Android devices.
The app is using ironSource mediation. With their AdMob adapter.

I am wondering if the Google Play Services version in your ANE is not compatible with the AdMob SDK version in their adapter?
What version of GPS does this ANE use?

12-05 14:00:59.211: E/AndroidRuntime(10790): FATAL EXCEPTION: main
12-05 14:00:59.211: E/AndroidRuntime(10790): Process: air.com.dg.obg.solitaire.quest.christmas.wonderland.story, PID: 10790
12-05 14:00:59.211: E/AndroidRuntime(10790): java.lang.NoSuchMethodError: No interface method pause(Landroid/content/Context;)V in class Lcom/google/android/gms/ads/reward/RewardedVideoAd; or its super classes

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
