### ISSUE TITLE
AchievementsEvents.LOAD event not getting called

### ISSUE THREAD

**Issue by Selonie** [myflashlab/GameServices-ANE#4]
Hi! I'm trying to get a list of unlocked achievements as per the onAchievementsLoaded function in the AchievementsSample.as and am getting no response. I get a successful init and login and can retrieve the player id etc, I can also load the native window using showNativeWindow() to view the achievements.

Can you confirm this works, and if so any ideas what I'm doing wrong? 
Testing on Android, with ANES from MyFlashLabClub_ANEs_packageV25.

**Comment by myflashlab** [comment]
Hi @Selonie While we upgraded the dependency ANEs to V9.6.1, we ran a test run on the gameServices ANE too. and everything works as expected! Please attach your device to your computer and run the logcat in Android Studio to see if any error logs are returned?

Yet, make sure you have added all the dependencies? (update your dependencies to V9.6.1 anyhow as it's the latest version)

also it's worthy to mention that if you have recently added the achievements to your panel, it might take some time before they can be seen by your application.

**Comment by Selonie** [comment]
Thanks for that, just to say it's now working, not sure why, I updated the dependencies, but I suspect it may have been due to having just added the achievements. Anyway thanks for the help.
