### ISSUE TITLE
iOS Crash on auth.login()

### ISSUE THREAD

**Issue by User3001** [myflashlab/GameServices-ANE#8]
I'm attempting to run the sample code for basic login, but instead get a crash with no error message when I try to run the sign in function. (Entire app crashes with no message, even running with debugger just insta-crashes.) The app opens and I can hit all sample buttons (although all output that "I must be logged in first."), and GameServices = SUCCESS on init. When I hit the login button (GameServices.google.auth.login();), it crashes/force closes the app.

permissionCheck.ane and gameServices.ane are both added, and I have installed the proper directories to the Air SDK and have both GoogleSignIn.bundle and gpg.bundle folders in the SWF directory. I've tested this on SDK 23 and 24 BETA and both have the same issue.

Here is my XML (Important/Sectet keys have been changed): http://pastebin.com/wNsNJc3B

Any help would be appreciated

P.S: I am not adding push notifications, as I assume they are optional.

**Comment by steven-cerebralfix** [comment]
I have this same issue on some Android devices, it hard crashes the device when I call GameServices.google.auth.login(). 
On other devices (Samsung Galaxy Tab3 - x86) I can call login() but it will display an Google Play error dialog:
"<game> is having trouble with Google Play services. If the problem persists, please contact the developer for assistance."
I'm using AIR 22, and not using permissionCheck.ane

**Comment by myflashlab** [comment]
This could happen if the required .frameworks are missing. Try connecting your device to xcode debugger and send us the output error message so we can investigate this more. This is the first time that someone is reporting something like this. So I guess something is missing in your setup.

**Comment by User3001** [comment]
I'm not aware of a way to connect the XCode debugger to a live iOS device running an Adobe Air app. Attached is the crashlog of the app.

[crashlog.txt](https://github.com/myflashlab/GameServices-ANE/files/607683/crashlog.txt)

**Comment by myflashlab** [comment]
The crashlog.txt is not showing any helpful notes as far as I can see. Anyhow, to see the xcode console window for all running tasks, connect your device to your mac, then in the xcode IDE go to Window -> Devices and from there open your connected device and it will show you all the ongoing logs. While seeing the logs, run the app and make the crash happen, there must be some logs about it in the console now as soon as the crash happens. Send us those logs for further investigation.

**Comment by User3001** [comment]
I've successfully caught the error with the xCode debugger. (My app XML and debug log can be downloaded below.)

At 07:32:18 I run the signin command and the errors afterwards occur.

One noteable line is " <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'You must specify |clientID| for |GIDSignIn|'" although i'm unsure if that details the cause.

Hopefully this will provide more info.

https://www.dropbox.com/s/wgukheajixa2f5g/files.zip?dl=0

**Comment by myflashlab** [comment]
Oh, today I looked again carefully at your manifest and noticed the problem! How I missed this the first time?!

The problem is that you have wrongly replaced some String keys that you shouldn't have.

Take the following as an example:
```xml
<key>com.google.android.gms.games.APP_ID</key>
<string>547360250816-d3gtu2bgtrql22dnr537dohoksl1lj9e.apps.googleusercontent.com</string>
```
You have also replaced the ```APP_ID``` which you shouldn't have. The result is that Google can't read the values. To fix the problem, study here again https://github.com/myflashlab/GameServices-ANE/wiki/A.-Preparing-the-Adobe-Air-side#configuring-the-air-manifest-xml-file but this time make sure you are setting things correctly. To know that, compare your final manifest with the demo one we have [here](https://github.com/myflashlab/GameServices-ANE/blob/master/FD/application.xml).

**Comment by User3001** [comment]
Thank you for noticing this. I've made the change and all is working now. When reading the Wiki I was under the impression that APP_ID had to be replaced, however obviously this is not the case.
