### ISSUE TITLE
RESULT_SIGN_IN_FAILED

### ISSUE THREAD

**Issue by ldevelop1966** [myflashlab/GameServices-ANE#9]
I have set up all correct, but i still get this message. The developer console (Google) says ready for test. 
My manifest is like the manifest in the description. Does anyone had the same issue and know the solution ?

**Comment by myflashlab** [comment]
Please let us know the following:

1. Are you testing on Android or iOS? or you are seeing ```RESULT_SIGN_IN_FAILED``` on both platforms?
2. Please post your manifest here so we can see if that is setup correctly? Are you sure you have copied your application ID into the manifest?

**Comment by ldevelop1966** [comment]
I am testing on Android and for sure - the appID is in the manifest:
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<application xmlns="http://ns.adobe.com/air/application/23.0">

	<id>com.ldevelop.Kopfrechnen</id>
	
	<filename>Kopftest</filename>
	<name>Kopftest</name>
		
	<versionNumber>0.9.9</versionNumber>
         
	
	<initialWindow>
		
		<content>[This value will be overwritten by Flash Builder in the output app.xml]</content>
		
		
	<autoOrients>false</autoOrients>
        <fullScreen>false</fullScreen>
        <visible>true</visible>
    </initialWindow>


	<icon>
			
				
				<image16x16>assets/icons/16.png</image16x16>
				<image32x32>assets/icons/32.png</image32x32>
				<image36x36>assets/icons/36.png</image36x36>
				<image48x48>assets/icons/48.png</image48x48>
				<image57x57>assets/icons/57.png</image57x57>
				<image72x72>assets/icons/72.png</image72x72>
				<image114x114>assets/icons/114.png</image114x114>
				<image128x128>assets/icons/128.png</image128x128>
				<image144x144>assets/icons/144.png</image144x144>
				<image192x192>assets/icons/192.png</image192x192>
				
				
	</icon> 
<android>
        <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
			<uses-sdk android:targetSdkVersion="23"/>
			  
			  <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	
	
	<uses-permission android:name="android.permission.GET_ACCOUNTS" />    
			
			      
 <application>
			
		
					
					 <activity>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
					

		<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 420274128168" />
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		
    	
</application>
			   
			    
			</manifest>
		]]></manifestAdditions>
    </android>
   
<extensions>
        
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.drive</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.games</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.plus</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.gameServices</extensionID>
    </extensions>
</application>

**Comment by myflashlab** [comment]
Ok, I can see that you are using ```<uses-sdk android:targetSdkVersion="23"/>``` which means if you are running on a device with Android Marshmallow or higher, you will need to use ```<extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>``` 

However, I don't think this would relate to the message you are receiving. Please also send us your AS code where you are trying to login and tell us on which listener you are seeing the ```RESULT_SIGN_IN_FAILED```?

**Comment by ldevelop1966** [comment]
package 
{
	import com.myflashlab.air.extensions.gameServices.GameServices;
	import com.myflashlab.air.extensions.gameServices.google.events.AuthEvents;
	import com.myflashlab.air.extensions.gameServices.google.player.PlayerLevel;
	
	

	public class MyGoogleGames
	{
		public function MyGoogleGames()
		{
			
		}
		
		public function init():void{
			
			trace("versuche Gameservice init");
			GameServices.init(false);
			GameServices.google.auth.addEventListener(AuthEvents.INIT, onInit);
			GameServices.google.auth.addEventListener(AuthEvents.TRYING_SILENT_LOGIN, onSilentTry);
			GameServices.google.auth.addEventListener(AuthEvents.LOGIN, onLoginSuccess);
			GameServices.google.auth.addEventListener(AuthEvents.ERROR, onLoginError);
		}
		
		public function login():void{
			GameServices.google.auth.login();
			
		}
		
		protected function onLoginError(e:AuthEvents):void
		{
			
			///HERE IS STOP - CANT LOGGIN !!!!
			
			trace("message: "+e.msg);
			
			trace("player: "+e.player);
			trace("LOGIN ERROR");
			
		}
		
		protected function onLoginSuccess(e:AuthEvents):void
		{
			
			
			trace("displayName = " +                e.player.displayName);
			trace("id = " +                         e.player.id);
			trace("title = " +                      e.player.title);
			trace("xp = " +                         e.player.xp);
			
			if (e.player.lastLevelUpTimestamp) // it will be null if the player has not leveled up yet!
			{
				trace("lastLevelUpTimestamp = " +   e.player.lastLevelUpTimestamp.toLocaleString());
			}
			
			var currLevel:PlayerLevel = e.player.currentLevel;
			trace("currLevel.levelNumber = " +      currLevel.levelNumber);
			trace("currLevel.minXp = " +            currLevel.minXp);
			trace("currLevel.maxXp = " +            currLevel.maxXp);
			
			var nextLevel:PlayerLevel = e.player.nextLevel;
			trace("nextLevel.levelNumber = " +      nextLevel.levelNumber);
			trace("nextLevel.minXp = " +            nextLevel.minXp);
			trace("nextLevel.maxXp = " +            nextLevel.maxXp);
			
		}		
		
		protected function onInit(e:AuthEvents):void
		{
			if (e.status == GameServices.SUCCESS)
			{
				//onSuccessfullInit();
				trace("INIT GOOGLE GAMES SUCCESS");
			}
			else
			{
				trace("there's something wrong!")
			}
			
			trace("onInit result = " + e.status);
			
		}
		
		protected function onSilentTry(e:AuthEvents):void
		{
			if (e.canDoSilentLogin)
			{
				// connecting to Game Services...
				// you should listen for the AuthEvents.LOGIN and AuthEvents.ERROR
				// to know the result of the sign-in process
				trace("SILENT LOGIN DURCHGEFÜHRT");
				
			}
			else
			{
				// If the ANE cannot sign-in the player automatically, you must place
				// a login button in your game screen so they can hit and sign-in manually.
				
				trace("LOGIN BUTTON NOTWENDIG");
				login();
				
				
			}
			
		}
	}
}

**Comment by myflashlab** [comment]
Aha, thanks for posting the AS codes. Well, after some Googling, it's now clear that the problem on your project is probably the result of some mismatching data. app version name, package name, anything like that might cause the problem. This error message is coming directly from the Google Play Services SDK.

check the following links:
* https://developers.google.com/android/reference/com/google/android/gms/games/GamesActivityResultCodes.html#RESULT_SIGN_IN_FAILED
* http://stackoverflow.com/questions/21019539/android-connect-to-gamecenter-with-statuscode-10002
* http://stackoverflow.com/questions/26446591/google-play-games-services-signin-randomly-stops-working-with-resultcode-games?rq=1

**Comment by ldevelop1966** [comment]
Yes, i know this links. Spend the whole last night with them. But if I have time, I ll try it again.

**Comment by myflashlab** [comment]
I would also try changing the Google account I'm testing with and also watch the logcat console on AndroidStudio, there might be more information there about what is causing the problem. let us know how it goes.

**Comment by ldevelop1966** [comment]
I still get the message Sign in failed. Meanwhile i purchased the Google Games Extension from Milkman. There is the same issue. 
For the FCM ane.  Milkmans EasyPush works, but with your FCM i get the token, but i cannot send a message. How can I solve this problems ?

**Comment by ldevelop1966** [comment]
with the Google Play ane , I had a short success yesterday. It logged in. but after that the error occured again.

**Comment by myflashlab** [comment]
As it seems there must be some issue with the Google users you're trying to connect. As we have ran a test run again and everything seems to be functioning correctly.

And as far as the FCM ANE, You should notice that FCM is a little bit different compared to GCM. (we also have a [GCM ANE you can find here](https://github.com/myflashlab/GCM-ANE).) Please provide more information about the FCM problem you are facing on its related issues page. We'll try to help you solve the problem as fast as possible.

**Comment by ldevelop1966** [comment]
I really dont know how to fix the problem, It can be a solution, if I grant
you access to my developer console. You are more experienced in your own
ane.
Can we do this ?

Best Regards
Andreas

2016-12-13 21:53 GMT+01:00 MyFlashLabs <notifications@github.com>:

**Comment by myflashlab** [comment]
Of course, we'd be happy to help. Please contact us through MyFlashLabs while referring to this issue. My colleagues should help you more. I guess I should close this issue now but as soon as we find what could be wrong in your setup, we'll update this ticket again so maybe it would help others also.
